/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mastermind;

import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    private static int mode = 2;
    private String name;
    private static ArrayList<String> username;
    private static ArrayList<String> score;
    Audio play = new Audio();
    
    public MainMenu() {
        initComponents();
        SettingPanel.setVisible(false);
        PlayPanel.setVisible(false);
        HowToPlay.setVisible(false);
        Scoreboard.setVisible(false);
        Score scoreboard = new Score();
        username = scoreboard.getUsername();
        score = scoreboard.getScore();
        for(int i = 0; i < 10 ; i++) {
            Name.append(username.get(i)+"\n");
            Score.append(score.get(i)+"\n");
        }
        play.music();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuSelector = new javax.swing.ButtonGroup();
        ModeSelector = new javax.swing.ButtonGroup();
        Scoreboard = new javax.swing.JPanel();
        TopScore = new javax.swing.JScrollPane();
        Score = new javax.swing.JTextArea();
        TopName = new javax.swing.JScrollPane();
        Name = new javax.swing.JTextArea();
        ScoreboarBG = new javax.swing.JLabel();
        EXIT = new javax.swing.JButton();
        Menu = new javax.swing.JPanel();
        PlayButton = new javax.swing.JToggleButton();
        SettingsButton = new javax.swing.JToggleButton();
        ScoreboardButton = new javax.swing.JToggleButton();
        HowToPlayButton = new javax.swing.JToggleButton();
        SettingPanel = new javax.swing.JPanel();
        Mode2 = new javax.swing.JToggleButton();
        Mode3 = new javax.swing.JToggleButton();
        Mode4 = new javax.swing.JToggleButton();
        Mode5 = new javax.swing.JToggleButton();
        Mode6 = new javax.swing.JToggleButton();
        Mode7 = new javax.swing.JToggleButton();
        Mode8 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        PlayPanel = new javax.swing.JPanel();
        Username = new javax.swing.JTextField();
        PlayOn = new javax.swing.JButton();
        BGPlay = new javax.swing.JLabel();
        HowToPlay = new javax.swing.JPanel();
        HTP = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mastermind");
        setMaximumSize(new java.awt.Dimension(1015, 800));
        setMinimumSize(new java.awt.Dimension(1015, 800));
        setPreferredSize(new java.awt.Dimension(1015, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Scoreboard.setOpaque(false);
        Scoreboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Score.setEditable(false);
        Score.setColumns(20);
        Score.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Score.setRows(5);
        Score.setAutoscrolls(false);
        TopScore.setViewportView(Score);

        Scoreboard.add(TopScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 300, 430));

        Name.setEditable(false);
        Name.setColumns(20);
        Name.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Name.setRows(5);
        Name.setAutoscrolls(false);
        TopName.setViewportView(Name);

        Scoreboard.add(TopName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 300, 430));

        ScoreboarBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/Scoreboard.png"))); // NOI18N
        Scoreboard.add(ScoreboarBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 710, 580));

        getContentPane().add(Scoreboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -20, 890, 620));

        EXIT.setBorder(null);
        EXIT.setContentAreaFilled(false);
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        getContentPane().add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 60, 60));

        Menu.setOpaque(false);
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuSelector.add(PlayButton);
        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/ButtonPlay.png"))); // NOI18N
        PlayButton.setBorder(null);
        PlayButton.setBorderPainted(false);
        PlayButton.setContentAreaFilled(false);
        PlayButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/ButtonPlayOn.png"))); // NOI18N
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });
        Menu.add(PlayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        MenuSelector.add(SettingsButton);
        SettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/ButtonSettings.png"))); // NOI18N
        SettingsButton.setBorder(null);
        SettingsButton.setBorderPainted(false);
        SettingsButton.setContentAreaFilled(false);
        SettingsButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/ButtonSettingsOn.png"))); // NOI18N
        SettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsButtonActionPerformed(evt);
            }
        });
        Menu.add(SettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));
        SettingsButton.getAccessibleContext().setAccessibleDescription("");

        MenuSelector.add(ScoreboardButton);
        ScoreboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/ButtonScoreboard.png"))); // NOI18N
        ScoreboardButton.setBorder(null);
        ScoreboardButton.setBorderPainted(false);
        ScoreboardButton.setContentAreaFilled(false);
        ScoreboardButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/ButtonScoreboardOn.png"))); // NOI18N
        ScoreboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScoreboardButtonActionPerformed(evt);
            }
        });
        Menu.add(ScoreboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        MenuSelector.add(HowToPlayButton);
        HowToPlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/ButtonHowToPlay.png"))); // NOI18N
        HowToPlayButton.setBorder(null);
        HowToPlayButton.setBorderPainted(false);
        HowToPlayButton.setContentAreaFilled(false);
        HowToPlayButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/ButtonHowToPlayOn.png"))); // NOI18N
        HowToPlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HowToPlayButtonActionPerformed(evt);
            }
        });
        Menu.add(HowToPlayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 800, -1));

        SettingPanel.setName(""); // NOI18N
        SettingPanel.setOpaque(false);
        SettingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ModeSelector.add(Mode2);
        Mode2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/Mode2.png"))); // NOI18N
        Mode2.setSelected(true);
        Mode2.setBorder(null);
        Mode2.setBorderPainted(false);
        Mode2.setContentAreaFilled(false);
        Mode2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/Mode2On.png"))); // NOI18N
        Mode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mode2ActionPerformed(evt);
            }
        });
        SettingPanel.add(Mode2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        ModeSelector.add(Mode3);
        Mode3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/Mode3.png"))); // NOI18N
        Mode3.setBorder(null);
        Mode3.setBorderPainted(false);
        Mode3.setContentAreaFilled(false);
        Mode3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/Mode3On.png"))); // NOI18N
        Mode3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mode3ActionPerformed(evt);
            }
        });
        SettingPanel.add(Mode3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        ModeSelector.add(Mode4);
        Mode4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/Mode4.png"))); // NOI18N
        Mode4.setBorder(null);
        Mode4.setBorderPainted(false);
        Mode4.setContentAreaFilled(false);
        Mode4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/Mode4On.png"))); // NOI18N
        Mode4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mode4ActionPerformed(evt);
            }
        });
        SettingPanel.add(Mode4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        ModeSelector.add(Mode5);
        Mode5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/Mode5.png"))); // NOI18N
        Mode5.setBorder(null);
        Mode5.setBorderPainted(false);
        Mode5.setContentAreaFilled(false);
        Mode5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/Mode5On.png"))); // NOI18N
        Mode5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mode5ActionPerformed(evt);
            }
        });
        SettingPanel.add(Mode5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        ModeSelector.add(Mode6);
        Mode6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/Mode6.png"))); // NOI18N
        Mode6.setBorder(null);
        Mode6.setBorderPainted(false);
        Mode6.setContentAreaFilled(false);
        Mode6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/Mode6On.png"))); // NOI18N
        Mode6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mode6ActionPerformed(evt);
            }
        });
        SettingPanel.add(Mode6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        ModeSelector.add(Mode7);
        Mode7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/Mode7.png"))); // NOI18N
        Mode7.setBorder(null);
        Mode7.setBorderPainted(false);
        Mode7.setContentAreaFilled(false);
        Mode7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/Mode7On.png"))); // NOI18N
        Mode7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mode7ActionPerformed(evt);
            }
        });
        SettingPanel.add(Mode7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        ModeSelector.add(Mode8);
        Mode8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/Mode8.png"))); // NOI18N
        Mode8.setBorder(null);
        Mode8.setBorderPainted(false);
        Mode8.setContentAreaFilled(false);
        Mode8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/Mode8On.png"))); // NOI18N
        Mode8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mode8ActionPerformed(evt);
            }
        });
        SettingPanel.add(Mode8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/ModePanel.png"))); // NOI18N
        SettingPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 6, 130, 420));

        getContentPane().add(SettingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, 460));

        PlayPanel.setOpaque(false);
        PlayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username.setText("Name");
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        PlayPanel.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 140, 30));

        PlayOn.setBorder(null);
        PlayOn.setBorderPainted(false);
        PlayOn.setContentAreaFilled(false);
        PlayOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayOnActionPerformed(evt);
            }
        });
        PlayPanel.add(PlayOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 80, 30));

        BGPlay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BGPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/PlayPanel.png"))); // NOI18N
        PlayPanel.add(BGPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 220, 330));

        getContentPane().add(PlayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 220, 350));

        HowToPlay.setOpaque(false);
        HowToPlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/HowToPlay.png"))); // NOI18N
        HowToPlay.add(HTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 560, 470));

        getContentPane().add(HowToPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 680, 500));

        BG.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermind/resources/bg.png"))); // NOI18N
        BG.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        if (evt.getSource() == EXIT) {
            dispose();
        }
    }//GEN-LAST:event_EXITActionPerformed

    private void Mode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mode2ActionPerformed
        mode = 2;
    }//GEN-LAST:event_Mode2ActionPerformed

    private void Mode3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mode3ActionPerformed
        mode = 3;
    }//GEN-LAST:event_Mode3ActionPerformed

    private void Mode4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mode4ActionPerformed
        mode = 4;
    }//GEN-LAST:event_Mode4ActionPerformed

    private void Mode5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mode5ActionPerformed
        mode = 5;
    }//GEN-LAST:event_Mode5ActionPerformed

    private void Mode6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mode6ActionPerformed
        mode = 6;
    }//GEN-LAST:event_Mode6ActionPerformed

    private void Mode7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mode7ActionPerformed
        mode = 7;
    }//GEN-LAST:event_Mode7ActionPerformed

    private void Mode8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mode8ActionPerformed
        mode = 8;
    }//GEN-LAST:event_Mode8ActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
          PlayPanel.setVisible(true);
          SettingPanel.setVisible(false);
          HowToPlay.setVisible(false);
          Scoreboard.setVisible(false);
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void SettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsButtonActionPerformed
        SettingPanel.setVisible(true);
        PlayPanel.setVisible(false);
        HowToPlay.setVisible(false);
        Scoreboard.setVisible(false);
    }//GEN-LAST:event_SettingsButtonActionPerformed

    private void PlayOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayOnActionPerformed
        name = Username.getText();
        Game execute = new Game();
        Score score = new Score();
        score.setName(name);
        score.setMode(mode);
        execute.setName(name);
        execute.setMode(mode);
        execute.setVisible(true);
        Codemaker start = new Codemaker(mode);
        start.Generator();
        this.setVisible(false);
        try {
            play.musicstop();
        } catch (InterruptedException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_PlayOnActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void HowToPlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HowToPlayButtonActionPerformed
        HowToPlay.setVisible(true);
        SettingPanel.setVisible(false);
        PlayPanel.setVisible(false);
        Scoreboard.setVisible(false);
    }//GEN-LAST:event_HowToPlayButtonActionPerformed

    private void ScoreboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScoreboardButtonActionPerformed
        SettingPanel.setVisible(false);
        PlayPanel.setVisible(false);
        HowToPlay.setVisible(false);
        Scoreboard.setVisible(true);           
    }//GEN-LAST:event_ScoreboardButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel BGPlay;
    private javax.swing.JButton EXIT;
    private javax.swing.JLabel HTP;
    private javax.swing.JPanel HowToPlay;
    private javax.swing.JToggleButton HowToPlayButton;
    private javax.swing.JPanel Menu;
    private javax.swing.ButtonGroup MenuSelector;
    private javax.swing.JToggleButton Mode2;
    private javax.swing.JToggleButton Mode3;
    private javax.swing.JToggleButton Mode4;
    private javax.swing.JToggleButton Mode5;
    private javax.swing.JToggleButton Mode6;
    private javax.swing.JToggleButton Mode7;
    private javax.swing.JToggleButton Mode8;
    private javax.swing.ButtonGroup ModeSelector;
    private javax.swing.JTextArea Name;
    private javax.swing.JToggleButton PlayButton;
    private javax.swing.JButton PlayOn;
    private javax.swing.JPanel PlayPanel;
    private javax.swing.JTextArea Score;
    private javax.swing.JLabel ScoreboarBG;
    private javax.swing.JPanel Scoreboard;
    private javax.swing.JToggleButton ScoreboardButton;
    private javax.swing.JPanel SettingPanel;
    private javax.swing.JToggleButton SettingsButton;
    private javax.swing.JScrollPane TopName;
    private javax.swing.JScrollPane TopScore;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
